name: pygeodata
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - rioxarray
  - geopandas
  - dask
  - zarr
  - pyarrow
  - filelock
  - graphviz
  - python-graphviz
  - pytest
  - fiona
  - libgdal-netcdf
  - pytest-mock
  - jupyter
  - flask
  - click
