name: release

on:
  push:
    tags: # trigger the deploy job on tag creation
      - v*
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml

  build:
    name: Build wheels
    uses: ./.github/workflows/build.yml

  build_dists:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist and wheel
        run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: dist-all
          path: dist/*

  upload_pypi:
    needs: [ test, build, build_dists ]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pygeodata
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks the sdist and every per-OS wheel into dist/
          pattern: dist-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
